services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shoes
    volumes:
      - storage_data:/var/www/html/storage
    networks:
      - custom-network
    env_file:
      - .env
    restart: always

  shoes_nginx:
    image: nginx:1.29.0-alpine
    container_name: shoes_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - storage_data:/var/www/html/storage
    depends_on:
      - app
    networks:
      - custom-network
    restart: always

networks:
  custom-network:
    external: true

volumes:
  storage_data:
